services:
  db:
    image: postgres:14
    container_name: dev-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dev-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4444:4444"
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: dev-frontend
    environment:
      HOST: 0.0.0.0
      VITE_API_BASE_URL: "http://backend:4444"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - app-network
    command: ["pnpm", "dev", "--host"]

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
